name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t demoforec2 . 
    - name: Tag Docker image
      run: docker tag $(docker images -q yuvasainath/demoforec2:latest) yuvasainath/demoforec2:latest
    - name: List Docker images
      run: docker images
    - name: Push Docker image
      run: docker push yuvasainath/demoforec2:latest
      
